import type { ServicePageProps } from "@/components/site/ServicePage";

export const SERVICE_PAGES: Record<string, ServicePageProps & { metaTitle: string; metaDesc: string; canonical: string }> = {
  "contabilidade-consultiva-brasilia": {
    metaTitle: "Contabilidade Consultiva em Brasília | Consync",
    metaDesc: "Contabilidade consultiva em Brasília. Indicadores, planejamento tributário e direcionamento estratégico para empresas que querem crescer.",
    canonical: "/contabilidade-consultiva-brasilia",
    eyebrow: "Contabilidade Consultiva · Brasília",
    title: "Contabilidade consultiva para empresas que querem crescer com clareza",
    intro:
      "Vá além das obrigações fiscais. A Consync atua como uma extensão estratégica do seu negócio, com indicadores claros e acompanhamento contínuo.",
    description:
      "Nossa contabilidade consultiva combina escrituração de qualidade, planejamento tributário, indicadores gerenciais e um consultor dedicado. Mais do que cumprir obrigações, ajudamos você a interpretar números, identificar oportunidades e decidir com segurança.",
    benefits: [
      "Consultor dedicado para a sua empresa",
      "Indicadores e relatórios gerenciais mensais",
      "Revisão tributária e oportunidades fiscais",
      "Apoio na tomada de decisões",
      "Visão estratégica de crescimento",
    ],
    forWho: [
      "Empresas em crescimento",
      "Prestadores de serviços e clínicas",
      "Escritórios e consultorias",
      "E-commerces e startups",
      "Empresas B2B",
      "Profissionais liberais com PJ",
    ],
    process: [
      { title: "Diagnóstico", text: "Entendimento do seu modelo, regime e prioridades." },
      { title: "Plano consultivo", text: "Definição de indicadores, calendário e implantação." },
      { title: "Implantação", text: "Migração, integração e organização da contabilidade." },
      { title: "Acompanhamento", text: "Reuniões periódicas com seu consultor dedicado." },
    ],
    faqs: [
      { q: "Qual a diferença para a contabilidade tradicional?", a: "A contabilidade tradicional foca em cumprir obrigações. A consultiva vai além: traduz números em direção, com indicadores, planejamento e acompanhamento contínuo." },
      { q: "Atendem empresas fora de Brasília?", a: "Sim. Atendemos clientes em todo o Brasil de forma 100% digital, mantendo Brasília/DF como sede." },
      { q: "Como é a periodicidade dos relatórios?", a: "Os relatórios gerenciais são entregues mensalmente, com reuniões periódicas combinadas no plano consultivo." },
    ],
  },
  "abertura-de-empresa-brasilia": {
    metaTitle: "Abertura de Empresa em Brasília | Consync Contabilidade",
    metaDesc: "Abertura de empresa em Brasília com a Consync. CNPJ, enquadramento tributário, CNAEs e orientação consultiva do início ao fim.",
    canonical: "/abertura-de-empresa-brasilia",
    eyebrow: "Abertura de Empresa · Brasília",
    title: "Abra sua empresa em Brasília com segurança e estratégia",
    intro: "Da escolha do regime tributário ao CNPJ ativo: a Consync conduz toda a abertura da sua empresa com agilidade e orientação consultiva.",
    description: "Cuidamos da estrutura societária, CNAEs, alvarás, inscrições e do enquadramento tributário mais adequado ao seu modelo de negócio. Você começa com a fundação certa para crescer.",
    benefits: [
      "Análise consultiva do modelo de negócio",
      "Definição do regime tributário ideal",
      "Escolha estratégica de CNAEs",
      "Acompanhamento até o CNPJ ativo",
      "Orientação inicial sobre obrigações",
    ],
    forWho: [
      "Novos empreendedores",
      "Profissionais que vão abrir PJ",
      "Sócios constituindo nova empresa",
      "Migração de MEI para ME/EPP",
      "Filiais e novas operações",
    ],
    process: [
      { title: "Briefing", text: "Entendimento da atividade, sócios e expectativas." },
      { title: "Planejamento", text: "Estrutura societária, CNAEs e regime tributário." },
      { title: "Registro", text: "Junta Comercial, Receita e órgãos competentes." },
      { title: "Pós-abertura", text: "Orientação inicial e início da contabilidade." },
    ],
    faqs: [
      { q: "Quanto tempo leva para abrir uma empresa em Brasília?", a: "Em média entre 7 e 20 dias úteis, dependendo da atividade e dos órgãos envolvidos." },
      { q: "Posso abrir empresa morando em outro estado?", a: "Sim, desde que a sede da empresa seja em Brasília/DF. Conduzimos tudo de forma digital." },
      { q: "Vocês ajudam a escolher o regime tributário?", a: "Sim. Esta é uma das etapas mais importantes e fazemos uma análise consultiva considerando faturamento, atividade e perfil de despesas." },
    ],
  },
  "bpo-financeiro-brasilia": {
    metaTitle: "BPO Financeiro em Brasília | Consync",
    metaDesc: "BPO financeiro em Brasília: contas a pagar e receber, fluxo de caixa e relatórios. Organização e previsibilidade para sua empresa.",
    canonical: "/bpo-financeiro-brasilia",
    eyebrow: "BPO Financeiro · Brasília",
    title: "Organize o financeiro da sua empresa com a Consync",
    intro: "Tire a operação financeira do gargalo e ganhe previsibilidade. Nosso BPO cuida das rotinas e entrega indicadores claros.",
    description: "Assumimos a gestão das rotinas financeiras da sua empresa: contas a pagar e receber, conciliações bancárias, fluxo de caixa, emissão de boletos e relatórios. Você ganha previsibilidade, indicadores e tempo para focar no negócio.",
    benefits: [
      "Contas a pagar e receber organizadas",
      "Conciliação bancária diária",
      "Fluxo de caixa atualizado",
      "Relatórios financeiros mensais",
      "Processos padronizados e auditáveis",
    ],
    forWho: [
      "Pequenas e médias empresas",
      "Empresas em crescimento",
      "Clínicas e escritórios",
      "Prestadores de serviço",
      "E-commerces",
    ],
    process: [
      { title: "Diagnóstico financeiro", text: "Mapeamento de processos, sistemas e gargalos." },
      { title: "Implantação", text: "Padronização de rotinas e integração de sistemas." },
      { title: "Operação", text: "Execução diária das rotinas financeiras." },
      { title: "Indicadores", text: "Relatórios mensais e reuniões de acompanhamento." },
    ],
    faqs: [
      { q: "Vocês utilizam algum sistema específico?", a: "Trabalhamos com os principais ERPs do mercado e podemos sugerir o mais adequado ao seu porte." },
      { q: "Como funciona a segurança das informações?", a: "Adotamos boas práticas de segurança da informação, LGPD e acessos segmentados por perfil." },
      { q: "É possível contratar apenas algumas rotinas?", a: "Sim. O escopo é modular e definido conforme a necessidade da sua empresa." },
    ],
  },
  "planejamento-tributario-brasilia": {
    metaTitle: "Planejamento Tributário em Brasília | Consync",
    metaDesc: "Planejamento tributário em Brasília. Reduza riscos, escolha o melhor regime e ganhe eficiência fiscal com a Consync.",
    canonical: "/planejamento-tributario-brasilia",
    eyebrow: "Planejamento Tributário · Brasília",
    title: "Planejamento tributário consultivo para reduzir riscos e otimizar custos",
    intro: "Pague o que é devido — e nem um centavo a mais. Avaliamos o seu modelo e indicamos o melhor regime e estratégia tributária.",
    description: "Analisamos sua operação, faturamento, despesas e estrutura societária para indicar o regime tributário mais adequado e oportunidades legais de eficiência fiscal. Tudo com base técnica e segurança jurídica.",
    benefits: [
      "Análise técnica do regime tributário",
      "Comparativos entre Simples, Lucro Presumido e Real",
      "Identificação de oportunidades fiscais",
      "Redução de riscos e contingências",
      "Apoio para tomada de decisão estratégica",
    ],
    forWho: [
      "Empresas em crescimento de faturamento",
      "Prestadores de serviços",
      "Comércio e e-commerce",
      "Empresas B2B",
      "Holdings e empresas com múltiplas operações",
    ],
    process: [
      { title: "Coleta de dados", text: "Faturamento, despesas, folha e estrutura societária." },
      { title: "Análise técnica", text: "Comparativos e simulações entre regimes." },
      { title: "Recomendação", text: "Apresentação consultiva com cenários." },
      { title: "Implantação", text: "Mudança de regime e acompanhamento." },
    ],
    faqs: [
      { q: "De quanto em quanto tempo vale a pena revisar?", a: "Recomendamos uma revisão anual e sempre que houver mudanças relevantes no faturamento, estrutura ou atividade." },
      { q: "Planejamento tributário é o mesmo que sonegação?", a: "Não. Planejamento tributário é a aplicação de práticas legais para reduzir a carga, sempre dentro da legislação." },
      { q: "Vocês acompanham mudanças na legislação?", a: "Sim. Acompanhamos a legislação federal, estadual e municipal e revisamos o impacto na sua empresa." },
    ],
  },
  "contabilidade-para-prestadores-de-servicos": {
    metaTitle: "Contabilidade para Prestadores de Serviços | Consync",
    metaDesc: "Contabilidade especializada para prestadores de serviços, profissionais liberais, clínicas e escritórios em Brasília.",
    canonical: "/contabilidade-para-prestadores-de-servicos",
    eyebrow: "Prestadores de Serviços",
    title: "Contabilidade especializada para prestadores de serviços",
    intro: "Atendemos profissionais liberais, consultores, clínicas, escritórios e empresas de serviços com soluções sob medida.",
    description: "Conhecemos os desafios específicos dos prestadores de serviços: tributação, retenções, ISS, regime de competência, gestão de honorários e fluxo de caixa. Entregamos uma contabilidade que organiza, protege e acelera.",
    benefits: [
      "Enquadramento tributário adequado",
      "Gestão de retenções e ISS",
      "Emissão e controle de notas",
      "Indicadores de honorários",
      "Apoio fiscal consultivo",
    ],
    forWho: [
      "Profissionais liberais",
      "Médicos e clínicas",
      "Advogados e escritórios",
      "Consultores e analistas",
      "Empresas de tecnologia e serviços",
    ],
    process: [
      { title: "Diagnóstico", text: "Avaliação do enquadramento atual e oportunidades." },
      { title: "Plano", text: "Organização tributária, fiscal e financeira." },
      { title: "Implantação", text: "Migração de dados e ajuste de processos." },
      { title: "Operação consultiva", text: "Rotina contábil e acompanhamento próximo." },
    ],
    faqs: [
      { q: "Atendem médicos e clínicas?", a: "Sim. Temos experiência com profissionais da saúde e estrutura adequada para clínicas em Brasília." },
      { q: "Cuidam de retenções de ISS?", a: "Sim. Apoiamos no controle, escrituração e cumprimento de obrigações relacionadas." },
      { q: "Posso migrar de MEI para ME com vocês?", a: "Sim. Conduzimos toda a transição com planejamento tributário e ajustes operacionais." },
    ],
  },
  "contabilidade-para-empresas-em-crescimento": {
    metaTitle: "Contabilidade para Empresas em Crescimento | Consync",
    metaDesc: "Contabilidade para empresas em crescimento em Brasília. Organização, previsibilidade e suporte estratégico para escalar.",
    canonical: "/contabilidade-para-empresas-em-crescimento",
    eyebrow: "Empresas em Crescimento",
    title: "Contabilidade para empresas que estão escalando",
    intro: "Crescimento exige organização. A Consync oferece estrutura contábil, indicadores e direcionamento para sua empresa escalar com segurança.",
    description: "Apoiamos empresas em fase de crescimento com uma estrutura contábil sólida, processos organizados e indicadores claros. Vamos além das obrigações para conectar contabilidade, financeiro e estratégia.",
    benefits: [
      "Estrutura contábil pronta para crescer",
      "Indicadores e relatórios estratégicos",
      "Planejamento tributário recorrente",
      "Apoio em decisões de investimento",
      "Governança e organização societária",
    ],
    forWho: [
      "Empresas em expansão",
      "Startups em fase de tração",
      "E-commerces escalando",
      "Empresas B2B com nova operação",
      "Empresas que receberam investimento",
    ],
    process: [
      { title: "Diagnóstico de crescimento", text: "Avaliação da maturidade contábil e financeira." },
      { title: "Plano", text: "Indicadores, governança e estratégia tributária." },
      { title: "Implantação", text: "Sistemas, processos e times integrados." },
      { title: "Acompanhamento estratégico", text: "Reuniões periódicas com indicadores e cenários." },
    ],
    faqs: [
      { q: "Atendem empresas que receberam investimento?", a: "Sim. Estruturamos a contabilidade e governança para atender requisitos de investidores e auditorias." },
      { q: "Como funcionam as reuniões estratégicas?", a: "Reuniões periódicas com seu consultor para analisar indicadores, cenários tributários e próximas decisões." },
      { q: "Conseguem acompanhar um crescimento rápido?", a: "Sim. Temos estrutura, processos e tecnologia para acompanhar a velocidade de empresas em expansão." },
    ],
  },
};
